import Head from 'next/head'
import styles from '@/styles/index.module.css'


export default function HomePage() {

  return (
    <>
      <Head>
        <title>Flash Chords</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
      </Head>
      <main className={styles.main}>
      </main>
    </>
  )
}
