import Head from 'next/head'
import '@/styles/index.module.css'
import {styled} from "@mui/material/styles";
import React from "react";
import PracticePage from "@/components/practice/PracticePage";
import {Chord, toChord} from "@/lib/music/Chord";
import {GetStaticProps} from "next";


const StyledRoot = styled('div')({
  display: "flex",
  flexDirection: "column",
  textAlign: "center",
  justifyContent: "space-between",
  width: '100%',
  height: '1000px',
})

export const getStaticProps: GetStaticProps = () => {
  return {
    props: {
      initialChord: toChord("Dbmaj7")
    }
  }
}

export default function HomePage({initialChord = toChord("Dbmaj7")}: { initialChord?: Chord }) {
  return (
    <>
      <Head>
        <title>Flash Chords</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
      </Head>
      <StyledRoot>
        <PracticePage initialChord={initialChord}/>
      </StyledRoot>
    </>
  )
}
